// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlogPost = "blog_posts"

// BlogPost mapped from table <blog_posts>
type BlogPost struct {
	PostID     int32     `gorm:"column:post_id;type:INTEGER;primaryKey" json:"post_id"`
	UserID     int32     `gorm:"column:user_id;type:INTEGER;not null" json:"user_id"`
	CategoryID int32     `gorm:"column:category_id;type:INTEGER;not null" json:"category_id"`
	Title      string    `gorm:"column:title;type:TEXT;not null" json:"title"`
	Content    string    `gorm:"column:content;type:TEXT;not null" json:"content"`
	CreatedAt  time.Time `gorm:"column:created_at;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName BlogPost's table name
func (*BlogPost) TableName() string {
	return TableNameBlogPost
}
