// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID  int32     `gorm:"column:category_id;type:INTEGER;primaryKey" json:"category_id"`
	Name        string    `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description string    `gorm:"column:description;type:TEXT;not null" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
