// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	CommentID int32     `gorm:"column:comment_id;type:INTEGER;primaryKey" json:"comment_id"`
	PostID    int32     `gorm:"column:post_id;type:INTEGER;not null" json:"post_id"`
	UserID    int32     `gorm:"column:user_id;type:INTEGER;not null" json:"user_id"`
	Content   string    `gorm:"column:content;type:TEXT;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
