// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePostTag = "post_tags"

// PostTag mapped from table <post_tags>
type PostTag struct {
	PostID int32 `gorm:"column:post_id;type:INTEGER;primaryKey" json:"post_id"`
	TagID  int32 `gorm:"column:tag_id;type:INTEGER;not null" json:"tag_id"`
}

// TableName PostTag's table name
func (*PostTag) TableName() string {
	return TableNamePostTag
}
